### PR TITLE
added subscriber classes, fixed autloader and fixed deprecated Shopware() calls

### PR DESCRIPTION
**Pull request by ghost**
Hi,

first of all thank you for that great plugin!

I fixed some several things, because it didn't work for me. This pull requests fixes the following things:

- added / refactored to subscriber classes
- fixed PSR-2 issues on touched classes (only one blank line between namespace and use statements)
- fixed deprecated Shopware() calls (moved to container usage as a dependency injection)
- fixed composer autoloader import, which was missing in order to get the plugin running
- system independend path separator
- realpath resolution on relative paths (which may cause error on some systems)

I got one issue left: Maybe you could look at composer autoloader class resolution, because for the Container class I needed the fully qualified path with leading backslash. If you leave out the leading backslash, composer searches the container class inside Port1HybridAuth.
I mean if you write this:
`use Shopware\Components\DependencyInjection\Container`
php says, that Container is not defined in namespace Port1HybridAuth, but if you use this: `use \Shopware\Components\DependencyInjection\Container` it works. Since I have never done resursively composer inclusion in a project before, this is new to me. So, I believe that this is an recursion class resolution error and could be fixed in composer.json.

These changes were tested on a production shop, using Shopware 5.3.4 with 20+ other plugins installed. It worked great with the facebook provider.

Best Regards

### CODE REVIEW

**Comment by EvilBMP** [comment]
> fixed composer autoloader import, which was missing in order to get the plugin running

I don't get the point here - the plugin should be installed via composer itself. There is a composer.json in the docroot directory of each Shopware installation. So for the latest stable version simply run 

`composer require --update-no-dev portrino/shopware-hybrid-auth:"~1.2.3"` 

in the Shopware docroot and the plugin gets automatically downloaded via packagist and installed in the correct path incl. correct autoloading. This is the way the plugin should be integrated using composer. 

Therefor the `require_once` condition should be removed IMHO.

**Comment by ghost** [comment]
Ok, well, but it isn't mentioned anywhere. In your readme you wrote "get the plugin from the Shopware Store". So, I assumed that this plugin is installable as usually via the plugin manager in Shopware backend.

**Comment by EvilBMP** [comment]
Aaah, sorry about that. The plugin was once a paid plugin in the Shopware store before we decided to make it open source. The readme is not updated yet. I'll open an issue for that.

**Comment by ghost** [comment]
If you do so, please fix in README.md also callback URL(s). I found an mistake for provider Google. Maybe there are more...
However, what is about the pull request? I found this method of including resursively used composer dependencies from FroshProfiler. A pretty good debugging plugin for Shopware, which you could install to you Shopware instance in both ways (composer and Plugin Manager).

**Comment by EvilBMP** [comment]
> However, what is about the pull request?

Have you checked my pull request on your pull request/ branch in your repo yet?

**Comment by EvilBMP** [comment]
> I found this method of including resursively used composer dependencies from FroshProfiler.

I had a look at the FroshProfiler readme.md - I'll test these three different installation methods in a local environment. But today I don't have time for this. Maybe at the weekend...

**Comment by ghost** [comment]
Ok, I have now seen your pull request on my fork. Well, it looks pretty well. I have only a few notices on that PR, so please review and fix it.

PS: Please help me / guide me a bit, I am new to that GitHub pull request work flow. I only used Bitbucket before (with their pull request work flow). Also, I never did forking before.

**Comment by ghost** [comment]
@EvilBMP I have accepted your pull request. Now, may you please accept mine, too?

**Pull request merged**
